# Generated by Django 5.2.6 on 2025-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registrocontable_fecha_pago_registrocontable_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocontable',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
