# Generated by Django 5.2.6 on 2025-10-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registrocontable_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
