# Generated by Django 5.2.6 on 2025-10-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_registrocontable_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivocargado',
            old_name='tamano',
            new_name='tamaño',
        ),
        migrations.AlterField(
            model_name='archivocargado',
            name='tipo_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
