# Generated by Django 5.2.6 on 2025-10-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_rename_tamaño_archivocargado_tamano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivocargado',
            old_name='tamano',
            new_name='tamaño',
        ),
    ]
