# Generated by Django 5.2.6 on 2025-10-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_rename_tamano_archivocargado_tamaño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivocargado',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
