# Generated by Django 5.2.6 on 2025-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_rename_tamaño_archivocargado_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocargado',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivocargado',
            name='datos',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
