# Generated by Django 5.2.6 on 2025-10-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_remove_archivocargado_archivo_archivocargado_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocargado',
            name='datos',
        ),
        migrations.AddField(
            model_name='archivocargado',
            name='archivo',
            field=models.FileField(default='archivos/default.txt', upload_to='archivos/'),
            preserve_default=False,
        ),
    ]
