# Generated by Django 5.2.6 on 2025-10-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_remove_archivocargado_datos_archivocargado_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocontable',
            old_name='persona_no_registrada',
            new_name='PersonaNoRegistrada',
        ),
    ]
