# Generated by Django 5.2.6 on 2025-10-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_rename_persona_no_registrada_registrocontable_personanoregistrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocargado',
            name='datos',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
