# Generated by Django 5.2.6 on 2025-10-14 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_archivocargado_datos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocargado',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='archivocargado',
            name='procesado',
        ),
        migrations.RemoveField(
            model_name='archivocargado',
            name='registros_creados',
        ),
        migrations.AlterField(
            model_name='archivocargado',
            name='subido_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
