# Generated by Django 5.2.6 on 2025-10-14 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_alter_archivocargado_subido_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocargado',
            name='datos',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivocargado',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivocargado',
            name='registros_creados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archivocargado',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
