# Generated by Django 5.2.6 on 2025-10-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_archivocargado_datos_archivocargado_procesado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocargado',
            name='datos',
        ),
    ]
