# Generated by Django 5.2.6 on 2025-10-14 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_remove_archivocargado_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocontable',
            name='archivo_origen',
        ),
        migrations.AddField(
            model_name='registrocontable',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='registros.archivocargado'),
        ),
    ]
