# Generated by Django 5.2.6 on 2025-10-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0018_remove_registrocontable_archivo_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocargado',
            name='datos',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
