# Generated by Django 5.2.6 on 2025-10-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_archivocargado_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocontable',
            old_name='PersonaNoRegistrada',
            new_name='persona_no_registrada',
        ),
    ]
