# Generated by Django 5.2.6 on 2025-11-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='backup',
            name='ruta',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
