# Generated by Django 5.2.6 on 2025-10-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_personanoregistrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='personanoregistrada',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
