# Generated by Django 5.2.6 on 2025-11-11 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena_anterior', models.CharField(max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contrasenas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
