# Generated by Django 5.2.6 on 2025-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_historialcontrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcontrasena',
            name='correo_usuario',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialcontrasena',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
