# Generated by Django 5.2.6 on 2025-11-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_historialcontrasena_correo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcontrasena',
            name='correo_usuario',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
