# Generated by Django 5.2.6 on 2025-11-11 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_historialcontrasena_correo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcontrasena',
            name='correo_usuario',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialcontrasena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='historialcontrasena',
            table='usuarios_historialcontrasena',
        ),
    ]
