# Generated by Django 5.2.6 on 2025-11-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_historialcontrasena_correo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcontrasena',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
